### PR TITLE
Upgraded to use vavr 0.10.0

### PR DESCRIPTION
**Pull request by longliveenduro**

### CODE REVIEW

**Comment by mvh77** [comment]
I don't understand the point of this PR. Why a major release for a transitive dependency change to a minor version?

**Comment by longliveenduro** [comment]
> I don't understand the point of this PR. Why a major release for a transitive dependency change to a minor version?

Happy to change the version to another one you would prefer

**Comment by longliveenduro** [comment]
@mvh77 changed it to 2.1.1

**Comment by mvh77** [comment]
The problem is that there is no backwards compatibility issue AFAIK, you can use vavr 0.10, just put that in your pom.xml. I'd wait for vavr 1.0 and then release 3.0 to use that.

**Pull request closed without merging**
